### ISSUE TITLE
App in play store is locked down to Israeli Google accounts

### ISSUE THREAD

**Issue by thesourcerer** [MohGovIL/hamagen-react-native#10]
Why not open to all countries?
Some of us are  using Non Israeli google accounts in the phone due to needing american apps.
Also, there might be foreign people in Israel with  foreign accounts as well, who currently live here, and should use the app as well.

**Comment by thesourcerer** [comment]
![magenBlocked](https://user-images.githubusercontent.com/1069188/77261522-b160e400-6c97-11ea-9c64-fc392b59a414.jpeg)

**Comment by MiriShalev** [comment]
Thanks! The reason for this is that many of us have their Play Store set in a different location than Israel. We changed the app to be available world-wide. It takes some time to propagate.

**Comment by thesourcerer** [comment]
> Thanks! The reason for this is that many of us have their Play Store set in a different location than Israel. We changed the app to be available world-wide. It takes some time to propagate.

@MiriShalev , any idea how much time it usually takes for this to update ? so far no change...

**Comment by chiptus** [comment]
still no change
