### ISSUE TITLE
Add stats feature to App

### ISSUE THREAD

**Issue by omribenm** [MohGovIL/hamagen-react-native#102]
Hi, we are 4 developers team that would like to contribute to the app, we have been thinking off adding some stats about the coronavirus to the app like amount off sick people in each area or in general, is there any API we could use? let us know what you think about the idea, or if you have a different idea that you want to develop, thanks.

**Comment by AlmaMOH** [comment]
Hey @omribenm,

Apologies for the late response.

Your offer sounds great. I'll pass it along to our management. Although I do think that our main mission is to stabilize what's working now and create a better development environment (See #101 , #95 , #96 ).

Currently there's a simple JSON file that contains the validated COVID-19 patients locations and time durations.

~~~bash
$ curl https://gisweb.azureedge.net/Points.json
~~~
