### ISSUE TITLE
Possible daylight savings issue

### ISSUE THREAD

**Issue by YarinKR** [MohGovIL/hamagen-react-native#103]
It seems that in SampleService.ts it is hard coded to add 2 hours to the timestamp, which I believe represents the time at UTC+0. Since we're entering daylight savings time this Friday, this may cause discrepancies between the timelines of the user and the confirmed Coronavirus carriers.

**Comment by kaplanlior** [comment]
https://github.com/MohGovIL/hamagen-react-native/blob/a7b7e6da0c3f8590e7663876ac7d1a4480651f64/src/services/SampleService.ts#L47

**Comment by R5n3h** [comment]
I think the right approach to this is to use the device locale with "moment" perhaps.
@MiriShalev what do you think? if you guys agree with this, I can do it and submit a PR.

**Comment by kaplanlior** [comment]
At the moment, I would keep it quite naive - if date equal / bigger than March 26th and smaller than October 25th - add 3. Should be a simple if. Quick and dirty :P

The longer version to be to increase them time difference on upgrade to align all past (relevant) examples.

**Comment by exx8** [comment]
why won't you use Date class? and make the conversion there?

**Comment by greenyossi** [comment]
This issue is fixed in the next release (See PR #124 ).
