### ISSUE TITLE
Documentation of how the app works

### ISSUE THREAD

**Issue by ey51** [MohGovIL/hamagen-react-native#109]
Is there an explanation anywhere on what exactly the app does?
- What data does it collect and record?
- How does it collect data when the app is closed? most mobile phones don't allow background processes to use location services.
- Does the app get location history access? is this data access even grantable?
- What's the internal algorithm to find matches between sick and unsick?

I would assume the mode of operation is as follows, but not sure if that's the case.
1. User consents to give app location history data (timestamps and locations)
2. Whenever a user is marked infected by the authorities, he is marked with the timestamp he was supposedly infected.
3. The recursive ReturnInfectedUsers(infected user, time of infection) method is called. it queries his route to find other users who have crossed paths with him since the time of infection (and remained near him for the required time threshold to be considered infected). For each infected user that is found, the process is repeated recursively.

Can someone verify?

**Comment by boynet** [comment]
nope, the data is never sent anywhere, only saved localy.. it uses your location history just to compare it to location the health care is publishing here:
https://govextra.gov.il/ministry-of-health/corona/corona-virus/spokesman-messages-corona/

**Comment by ey51** [comment]
> https://govextra.gov.il/ministry-of-health/corona/corona-virus/spokesman-messages-corona/
> and here:
> https://gisweb.azureedge.net/Points.json

1. how does the above list of points you mentioned get collected? via technological means or via questioning of the sick, and reliance on their memory?

2. i know the app has location permission, but how does it obtain location history (1) when the app is off, (2) history prior to installing the app?

**Comment by chpl** [comment]
https://medium.com/proferosec-osm/hamagen-application-fighiting-the-corona-virus-4ecf55eb4f7c

**Comment by AlmaMOH** [comment]
Hey @ey51 ,

Apologies for the late response.

I think that [Profero Sec's exlpanation](https://medium.com/proferosec-osm/hamagen-application-fighiting-the-corona-virus-4ecf55eb4f7c) of how Hamagen works and what gets collected is pretty good. Please let us know if you have anything you'd like to know more.

Regarding your other points, currently the app *does not* access your past history - but we are working on #124 which will allow a user to give the app access to his last 14 days of location history (only saved **locally**).

We know our current documentation isn't sufficient, please let us know where we can improve.

**Comment by ey51** [comment]
ack. thanks. stay safe
