### ISSUE TITLE
Suggestion: add support to several languages

### ISSUE THREAD

**Issue by mfrade** [MohGovIL/hamagen-react-native#110]
I salute the authors of this app for their contribution to help stop the COVID-19.
This app can also be useful in other countries, do you consider the possibility of adding support to several languages and request help from the open source community for the translation?

**Comment by AlmaMOH** [comment]
Thanks @mfrade !

Regarding the UI of the app, we currently have translations to: Hebrew, English, Arabic, Amharic, Russian, French.

The data of the validated COVID-19 patients comes directly from Israel's Ministry of Health and is the result of laborious epidemiological investigations. This data contains Hebrew texts which cannot be translated easily (specific locations, e.g. floor 4 at building X).

We accept translations for the UI from the Open Source community and in fact already incorporated French as a result (See #11 ).

I hope I answered your question.
