### ISSUE TITLE
Exporting User's Last 14 Days Locations using Google's Timeline  

### ISSUE THREAD

**Issue by AlmaMOH** [MohGovIL/hamagen-react-native#112]
Hey,

We're about to launch a feature which extracts a user's last 14 days locations through Google's Timeline.

Here's [the branch](https://github.com/MohGovIL/hamagen-react-native/tree/feature/14-days-location-history). 

We'd love you feedback / suggestions! 

Closing #92 , #76. 

MOH Team

**Comment by amitdadon** [comment]
@AlmaMOH would you open a P.R so we can review this branch?

**Comment by AlmaMOH** [comment]
@amitdadon sure! here's the PR #123 . Let's continue the discussion there (if anything arises).
