### ISSUE TITLE
?למה נתוני המפה אינם מעודכנים

### ISSUE THREAD

**Issue by danid12** [MohGovIL/hamagen-react-native#116]
קחו לדוגמא את הדיווחים על העיר רמלה:
https://www.gov.il/he/departments/news/ramle-corona
ואז תסתכלו על המפה:
https://imoh.maps.arcgis.com/apps/webappviewer/index.html?id=20ded58639ff4d47a2e2e36af464c36e&locale=he&/
ותחפשו שם רמלה ותראו שאף סופרמרקט ואף חנות שמופיעה בדיווח של משרד הבריאות אינה מופיעה על המפה!
ולכן נשאלת השאלה- האם האפליקציה מתבססת נטו על המפה הזאת או שיש מקורות נוספים משם היא שואבת את הנתונים?
אם זה רק על בסיס המפה הלא מעודכנת הזאת אז האפליקציה חסרת ערך וזאת הסיבה גם שכרגע אני נמנע מלהוריד אותה כי היא מבוססת על מידע חלקי ולא אמין.

**Comment by rafi** [comment]
לא מובן כל-כך על סוג החיתוכים והמידע שמשתמשת בו האפליקציה, יש תגובה [פה](https://github.com/MohGovIL/hamagen-react-native/issues/107#issuecomment-604352448) שאומרת שהמידע רק על מקומות ציבוריים, למשל. אבל נראה שתקבל גם התראות על הצלבה בין הנתונים ההיסטוריים שלך שהיא כבר אספה, לבין חולים שנמצאו רק עכשיו וניתוח המסלול שלהם בעבר, ולא רק מרגע שאובחנו. הדף הראשי של הפרוייקט מראה איך להוריד את מסד-הנתונים למחשבך. לבסוף, אני מרגיש שכל מידע עכשיו חשוב, וגם המסלולים שלך שנשמרים ומקבלים נופך שונה בכל אימות חולה חדש.

**Comment by DanielMOH** [comment]
הערות ושאלות טובות. אני אנסה להסביר ולעשות קצת סדר:
האפליקציה והמפה שמוצגת באתר משרד הבריאות ניזונות מאותו מקור נתונים. המיקומים שמופיעים כטקסט באתר משרד הבריאות מגיעים כרגע ממקור אחר. לצערנו, היה חוסר סנכרון בין שני המקורות הללו. מתבצע כעת מאמץ גדול לפתור את זה בהקדם. 
להתקנת האפליקציה כבר עכשיו יש חשיבות בכל מקרה, כדי שתתחיל לאגור (מקומית בטלפון שלך, כמובן) את המיקומים שלך. גם אם יש מיקום של חולה שעדיין לא מופיע מאיזושהי סיבה בקובץ המיקומים, ברגע שהוא יעודכן והאפליקציה תמשוך את הקובץ המעודכן, תיבדק חפיפה של מיקומי המשתמש גם מול המיקום הזה (עד 14 יום לאחור), ואם תימצא חפיפה כזאת - תוצג התרעה.

לגבי בדיקת מסלולים היסטוריים ש-@rafi דיבר עליהם: בגרסה החדשה ששוחררה אתמול (ומתחילה להופיע בהדרגה בחנויות Google Play ו-Apple) נוספה כבר אפשרות לייבא אל האפליקציה את המיקומים שלך מ-14 הימים האחרונים, מתוך היסטוריית המיקומים (Timeline) שבחשבון Google שלך.
האפליקציה מבצעת בדיקת חפיפות בכל פעם שמתעדכנים נתוני חולים, אל מול כלל נתוני המיקום של המשתמש, עד 14 ימים לאחור - אלו שהיא שמרה מאז שהותקנה ואלו שיובאו מ-Google Timeline.
