### ISSUE TITLE
[Suggestion] Use third party SDK for location tracking to imrpove accuracy

### ISSUE THREAD

**Issue by yonidavidson** [MohGovIL/hamagen-react-native#129]
Hi, due  to complaints in location tracking, I suggest adding a third party SDK for location tracking:
https://radar.io/documentation/sdk#react-native
For example.

**Comment by AlmaMOH** [comment]
Hey @yonidavidson,

Thanks for suggesting that. 

Actually, at first, we did use radar - but eventually we discovered that **radar sends to their server the location data of users who install the app**!

So we end up using [TransistorSoft's react-native SDK](https://www.transistorsoft.com/shop/products/react-native-background-geolocation).
