### ISSUE TITLE
Fresh Start, Cannot make it run 

### ISSUE THREAD

**Issue by drixbarsali** [MohGovIL/hamagen-react-native#139]
Cloned.
Yarn
cd ios
pod install
cd ..
yarn ios OR react-native run-ios --scheme hamagen

![image](https://user-images.githubusercontent.com/6553988/77995442-14074f00-732c-11ea-8f71-4e9ec778405a.png)

**Comment by emanuelb** [comment]
1. Try to clone the project again, it helped with related issue, see:
https://github.com/MohGovIL/hamagen-react-native/issues/132 Help needed with running the app on android "Invariant Violation"
2. see also related issue:
https://github.com/MohGovIL/hamagen-react-native/issues/37 [iOS] Can't run the app locally - several issues with XCode/RN configuration
which contain pull request with fix that you can try:
https://github.com/MohGovIL/hamagen-react-native/pull/38 Fixes for iOS issues in dev, updated docs with iOS instructions

**Comment by drixbarsali** [comment]
Worked... Thank you
