### ISSUE TITLE
Adding Tigrinya (ትግርኛ) language support.

### ISSUE THREAD

**Issue by oyd11** [MohGovIL/hamagen-react-native#142]
Hello, I've started working on a Tigrinya translation for the application prompts.

This could be relevant as Tigrinya (ትግርኛ) is spoken both by 10-20% of the Ethiopian-Olim as a first language, and because it's the main language spoken by Eritrean-Migrants currently residing in Israel in several dense urban areas.

I've created a branch with initial translated prompted I've received from a translator, and I'm waiting for him to complete the translation; I have basic conversational skills in Tigrinya and I can verify some of the text, but I'm far from being fluent enough to translate myself. 

https://github.com/oyd11/hamagen-react-native/tree/add_tigrinya_language

I've discussed the translation issue with the organisation "Mesila" - and their translators are currently too busy with other Covid19 related material production.

As Tigrinya is generally a lesser known language, I'm pasting the information here: 
```
 ISO 639-1  ti
 ISO 639-2  tir
 ISO 639-3  tir
```
locale-code: `ti`
 * http://www.unicode.org/cldr/charts/31/summary/ti.html
 * http://www.localeplanet.com/icu/ti/index.html

**Comment by oyd11** [comment]
Can anyone merge this translation? It's verified since 5th-April-2020 (a little over a month),
and there's still a highly dense urban population which speaks this language predominantly, a lot of them working in the service industry now. Please merge.

**Comment by kaplanlior** [comment]
Hi @oyd11 , thanks for this issue and your effort (here and at #156 ). At the moment we don't accept any new translations. I'm adding a translations tag to this PR, so it could be used easily when translations would be accepted again.
