### ISSUE TITLE
Repeated Overlap Notifications

### ISSUE THREAD

**Issue by ItaySofer** [MohGovIL/hamagen-react-native#145]
The application notifies about a possible overlap with a Covid-19 patient.
After I acknowledge that I wasn't in the specified location, the same overlap notification keeps popping again from time to time.
I would expect it to remember my acknowledgement and not pop this notification anymore.

**Comment by magenapp** [comment]
Thanks for your comment, This issue resolved in version 1.1.2, currently available in apple store, will be available in google play soon

**Comment by ItaySofer** [comment]
Thanks
