### ISSUE TITLE
App keep nagging about previous, incorrect alerts

### ISSUE THREAD

**Issue by shirkan** [MohGovIL/hamagen-react-native#146]
My wife & I keep getting alerts about previous possible overlaps which are:
1. Old (more than 1 week old)
2. Incorrect

We dismiss them and they keep coming back every couple of hours.

**Comment by rafi** [comment]
@shirkan see #145 and #144

**Comment by shirkan** [comment]
> @shirkan see #145 and #144

got it, closing
