### ISSUE TITLE
looks that this compare function should use coordinates and not POINT_X, POINT_Y

### ISSUE THREAD

**Issue by akruman** [MohGovIL/hamagen-react-native#15]
https://github.com/MohGovIL/hamagen-react-native/blob/89561567328e7d07d06b5e7896b4942f1b9b347e/src/services/Tracker.ts#L50

by looking in this func, i can see that POINT_X and Y is taken from the sick record, 
but observing the db : https://gisweb.azureedge.net/Points.json
i notice that most of these points are either null or 0, the actual thing to compare probably is 
sickRecord.geometry.sickRecord[0] and [1]

**Comment by MiriShalev** [comment]
Thanks for spotting this! :)
