### ISSUE TITLE
Rebase greenyossi/react-native-extra-dimensions-android on master & look for other library

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/hamagen-react-native#158]
fork of react-native-extra-dimensions-android by user @greenyossi that located in
https://github.com/greenyossi/react-native-extra-dimensions-android.git is used in package.json
https://github.com/MohGovIL/hamagen-react-native/blob/0afc8cabc4ea82c8e3ef469f19f989c8c93de24e/package.json#L39

which contain 5 changes is based on old version
> This branch is 5 commits ahead, 47 commits behind Sunhat:master. 

The below 3 changes
https://github.com/Sunhat/react-native-extra-dimensions-android/commit/b3d98103607d61fe47cf3131ef3b1ea26e5685f3
https://github.com/Sunhat/react-native-extra-dimensions-android/commit/7f5038228d1fafad88f4838d61c0dc85cc1a7589
https://github.com/Sunhat/react-native-extra-dimensions-android/commit/e409c18c639ebf1c9d8ac69eb4d64f6b9c12bb3c

are already fixed/implemented in upstream version.

also upstream author say at "Mar 5, 2020" that:
https://github.com/Sunhat/react-native-extra-dimensions-android/issues/56#issuecomment-595434688

> Dead project. Nobody should use this.

so it's better to look for other library/solution.

**Comment by kaplanlior** [comment]
See MohGovIL/react-native-extra-dimensions-android#1
