### ISSUE TITLE
API keys committed

### ISSUE THREAD

**Issue by omerxx** [MohGovIL/hamagen-react-native#16]
https://github.com/MohGovIL/hamagen-react-native/blob/89561567328e7d07d06b5e7896b4942f1b9b347e/android/app/src/release/google-services.json#L106

**Comment by lidorbt** [comment]
https://github.com/zooniverse/vox/issues/32

https://medium.com/@paulbreslin/is-it-safe-to-expose-your-firebase-api-key-to-the-public-7e5bd01e637b

I noticed that you've opened 2 issues about it. I'm not an expert with firebase, but are you sure it's that dangerous to expose those keys..?

**Comment by MiriShalev** [comment]
Thanks for pointing that out @omerxx . Nevertheless, we agree with @lidorbt - all Firebase based apps expose such client tokens / api keys in client side.

**Comment by MiriShalev** [comment]
See also: https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public/37484053#37484053
