### ISSUE TITLE
Update Android Gradle plugin

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/hamagen-react-native#164]
currently used version is 3.4.2:
https://github.com/MohGovIL/hamagen-react-native/blob/9e70e2784d24d54a8b28f0a0d0c20f2f6562b982/android/build.gradle#L17

latest version is 3.6.0
https://developer.android.com/studio/releases/gradle-plugin#3-6-0

see upgrade instructions in:
https://developer.android.com/studio/releases/gradle-plugin#updating-plugin

**Comment by emanuelb** [comment]
Currently used version is 3.6.3:
https://github.com/MohGovIL/hamagen-react-native/blob/00896628cabd02a0017ccecdeab9f9cae342b680/android/build.gradle#L17
while latest is 4.0.1 (Released in July 2020) which require also to upgrade android buildToolsVersion to 29 (android 10) see issue #161

**Comment by kaplanlior** [comment]
Fixed. Change for 4.0 will wait for #161
