### ISSUE TITLE
Add Github topics to repo

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/hamagen-react-native#170]
improve project discoverability by adding github topics, see:
https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

covid-19 used topics are:
https://github.com/topics/covid
https://github.com/topics/covid-virus
https://github.com/topics/covid19
https://github.com/topics/covid-19
https://github.com/topics/corona
https://github.com/topics/coronavirus

related mobile topics are:
https://github.com/topics/react-native

**Comment by kaplanlior** [comment]
Thanks. Added covid-19 and coronavirus which seem the two most popular.
