### ISSUE TITLE
Enable Hermes 

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/hamagen-react-native#177]
Hermes is currently disabled at:
https://github.com/MohGovIL/hamagen-react-native/blob/694714f9e472a15dda66748edae7ed052b1bee8e/android/app/build.gradle#L81

information on how to enable it:
https://reactnative.dev/docs/hermes

**Comment by greenyossi** [comment]
Disabled hermes again, since it causes an issue with retrieving google timeline history.
