### ISSUE TITLE
Daylight saving time error 

### ISSUE THREAD

**Issue by hmgnuser** [MohGovIL/hamagen-react-native#179]
קיבלתי באפליקציה התראה על חשיפה בסופרפארם רמת אביב ביום שישי 3/4 בשעות 10-11.
במפת הקורונה מסומנת חשיפה באותו מקום בשעות 11-12. 
האם ייתכן שהשעון לפיו ההתראות נמסרות באפליקציה לא מסונכן עם שעון הקיץ?

**Comment by emanuelb** [comment]
כן, הבאג הזה תוקן בגרסא האחרונה, תבדוק האם זה משתחזר גם אחרי עדכון?
תוכל לקרוא כאן על הדיון המקורי
https://github.com/MohGovIL/hamagen-react-native/issues/103
