### ISSUE TITLE
Repeating overlap event (FP) in overlap history

### ISSUE THREAD

**Issue by OfirKP** [MohGovIL/hamagen-react-native#180]
Hi, I got the same issue as #167 (and perhaps it was solved in the last update), but the event (which was marked as FP) appears 3 times in the 'Overlap history' tab in the app. 
It's the same event with the same location, date and time.

## Screenshot
![image](https://user-images.githubusercontent.com/11351634/78458617-7610dd00-76bb-11ea-86fa-3d124eceb279.png)

**Comment by Eladkay** [comment]
I second this and attach a screenshot.
![91796121-1E7C-408E-AB79-169B9CF21E55](https://user-images.githubusercontent.com/11412452/78459828-8e392a00-76c4-11ea-9dc8-3c85eb675e14.png)

**Comment by kaplanlior** [comment]
Hi @OfirKP and @Eladkay, the issue was fixed in previous versions. Thanks for reporting.
