### ISSUE TITLE
Implementing Better API

### ISSUE THREAD

**Issue by ChayimFriedman2** [MohGovIL/hamagen-react-native#187]
Our API for check whether someone was in the same region with a corona-virus patient is very network -consuming. In order to check that, we send the whole table of patients (thousands of people!) to the client each hour! And we want millions of client! Even if Israel is a small country with few citizens, re-using the app for USA, for instance, will mean an unreliable app.

I know there are privacy-paranoids who afraid, for reason I don't (and probably never will) understand, that the government will know **where they were**. Wow. I agree that's very horrible. But after the jokes, I'm proposing a different approach:

Instead of sending the whole database to the client, the client will send its location, and the server will return the overlaps, if there are. Of course, the paranoids mentioned above will protest again this approach, and so I suggest the following thing:

Yeah, (assuming the API keeps track of our movement and save the information, which I don't believe for, but anyway they're believe, so...) the API can track our movement. But only if it _has access to our location in 100% sure every time_. What if it can **guess**, but **can't be sure**?

Let's simplify the things. If we're requesting from someone to notify us whether in Jerusalem, st. Some-Street, the road near house numbered 33, there was a corona-virus patient on Thursday, 15:00 o'clock - this person can, somehow (I guess), to know where we was on Thursday, 15:00 o'clock. Don't you agree?

But what if we're requesting him to notify us whether there were corona-virus patients on **both** Jerusalem, Some-Street, the road near house 33 **and** Tel Aviv, Some-Another-Street, house 24? Now the person can **guess** where we live, but cannot be more than 50% sure.

Let's go one step further. If we ask the person about 5 locations, can it even guess where the real location is?

I think you can understand the direction. If, instead of just sending one location, we send multiple, the API can't know where we are.

Yet this is not true. because, let me illustrate the following scenario:

The app was installed on 10:00. Four hours after, the API knows that:

 1. On 10:00, we were at either Jerusalem, Haifa or Tel Aviv.
 2. On 11:00, we were at either Jerusalem, Tel Aviv or Rosh Hanikra.
 3. On 12:00, we were at either Jerusalem, Ashdod, or Ramat Gan.
 4. On 13:00, we were at either Jerusalem, Rehovot or Raanana.
 5. On 14:00, we were at either Petah Tikva, Modiin, or Bnei Brak.

Do you see the problem? With this data, the API can easily guess that we're living at Jerusalem.

So, in order to prevent the API from tracking us, we need a way so even if it places crosswise the data across hours, still it can determine the real location.

Luckily, I've found a solution. Instead of just randomizing locations (apart from the real one), we'll do the following:

 1. When the app is installed:
    1. Save the user location as the previous location.
    2. Randomize other four locations. Save them (I haven't said it yet, but obviously the number five is, ah, randomized).
    3. Send the request.
 2. Every time we want to check for overlap:
    1. Calculate the distance and angle from the previous location.
    2. Replace the "previous location" variable with the current one.
    3. Add the distance to the four fictitious locations, and replace the variables of them.
    4. Send the request.

This way, the server can't track us, as we have consistent five locations that can the only thing differs them from being real, is the unfortunate fact that they're not.

I still have a problem because we can exceed the country borders in long travels. I don't have a solution yet, I hope one of the people here will have.

If this proposal is accepted, the problem above is solved, and the folks at the Ministry of Health changes the API so it accepts list of locations and returns their overlaps, I'm ready to work on that and send a PR.

**Comment by oleiba** [comment]
1) An anonymity set in the size of 5 (or even within tens, I would say) is too small to begin with.

2) Naive offsetting of geographic locations from randomized locations can very soon end-up in places that make zero-sense and would be easily ruled out by analysis of the request logs. Think crossing walls, walking on water, wandering around a kindergarten at night or a cemetery in the early morning.
A non-naive implementation, i.e. fitting locations into the randomized geographies so that they would make sense, will probably be an overkill.

3) There are other (IMHO more realistic) solutions that do not require sending _all_ the patients data every period of time. 
Mostly: incremental updates (as in https://github.com/MohGovIL/hamagen-react-native/issues/58) and Bluetooth proximity (as in https://github.com/MohGovIL/hamagen-react-native/issues/126).
