### ISSUE TITLE
I suppose keys should be redacted

### ISSUE THREAD

**Issue by omerxx** [MohGovIL/hamagen-react-native#20]
https://github.com/MohGovIL/hamagen-react-native/blob/c59aa1669deb2c20fbe229f65f6d812aa096df43/ios/codeAgainstCorona/firebase/release/GoogleService-Info.plist#L12

**Comment by MiriShalev** [comment]
Closing this issue by the same logic of the [comment](https://github.com/MohGovIL/hamagen-react-native/issues/16#issuecomment-602293136) (by @lidorbt).

**Comment by MiriShalev** [comment]
Also see: https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public/37484053#37484053
