### ISSUE TITLE
Use Gradle 'bin' DistributionType instead of 'all' at least for CI environments

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/hamagen-react-native#206]
Currently the DistributionType used is `all` at:
https://github.com/MohGovIL/hamagen-react-native/blob/c59aa1669deb2c20fbe229f65f6d812aa096df43/android/gradle/wrapper/gradle-wrapper.properties#L3
which might be useful in IDE usage, but not needed in CI (automated builds/tests).

https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/wrapper/Wrapper.DistributionType.html#enum.constant.summary
> ALL | complete Gradle distribution with binaries, sources and documentation
BIN | binary-only Gradle distribution without sources and documentation

See here how to customize the wrapper task to generate the desired DistributionType:
https://docs.gradle.org/current/userguide/gradle_wrapper.html#customizing_wrapper

**Comment by kaplanlior** [comment]
Fixed at ef6c7964c85d4e516c7ddd344290bb03b69ed815
