### ISSUE TITLE
Use ExposureNotification API?

### ISSUE THREAD

**Issue by dotansimha** [MohGovIL/hamagen-react-native#216]
Apple introduced a new API for exposure notifications: https://developer.apple.com/documentation/exposurenotification

And for android: https://blog.google/documents/68/Android_Exposure_Notification_API_documentation_v1.2.pdf

There is also an integration for RN: https://github.com/codejamninja/react-native-exposure-notification

**Comment by kaplanlior** [comment]
Thanks @dotansimha , also notice this API requires some restriction on how the application can/can't work. Also see #190 reported earlier.

**Comment by gadicc** [comment]
Can I suggest we close this issue and amend #190's title to include "Exposure Notifications API".
