### ISSUE TITLE
[Translation]French correction in Additional Privacy information Menu

### ISSUE THREAD

**Issue by ilanenadjar** [MohGovIL/hamagen-react-native#226]
you need to change the "Home" in burger menu : In french translation is "Accueil" not "Acceuil"
![IMG_20200708_082603](https://user-images.githubusercontent.com/11611117/86880479-6dcea080-c0f5-11ea-8793-2e64067eb6b8.jpg)

**Comment by ilanenadjar** [comment]
by the Way... Great Job ! Nice simply app.

**Comment by kaplanlior** [comment]
Thanks for the typo notice, confirmed also with https://en.wiktionary.org/wiki/accueil

**Comment by kaplanlior** [comment]
@ilanenadjar This change is in the MOH website, not in the software directly. We've passed the request and I expect it to get fixed quite soon. Thanks again for the feedback (:

I'm closing this issue for now, as the change isn't in the app itself. Feel free to ping me here again if needed.

**Comment by ilanenadjar** [comment]
This is why I did not find this translation in the application code ;) thank you @kaplanlior

**Comment by kaplanlior** [comment]
![index](https://user-images.githubusercontent.com/2017058/87005374-92934880-c1c7-11ea-8aac-1fc33116b60e.jpeg)
Translation fixed on the website...

**Comment by ilanenadjar** [comment]
Nice job
