### ISSUE TITLE
[Help wanted] Amharic translation (BLE, GPS & Network)

### ISSUE THREAD

**Issue by kaplanlior** [MohGovIL/hamagen-react-native#227]
Hi,

We're looking for people who can help with improving our Amharic translation for Hamagen. We'd like to focus on these new strings added in version 2.0. While we really love Git pull requests, we know not everyone are fluent with Git work. Feel free to leave comments with the translation, we'll make sure it goes into the app.

Translation:
https://github.com/MohGovIL/hamagen-react-native/blob/e5606f3040c47b5c2713d432280273a99bcb2285/src/locale/texts.json#L1207-L1212

Context:
![1](https://user-images.githubusercontent.com/2017058/87294179-086f1b00-c50c-11ea-8307-150d7e5cfd3e.jpg)

Translation:
https://github.com/MohGovIL/hamagen-react-native/blob/e5606f3040c47b5c2713d432280273a99bcb2285/src/locale/texts.json#L1288-L1295

Context:
![2](https://user-images.githubusercontent.com/2017058/87294192-0b6a0b80-c50c-11ea-9980-7d17a56d0a65.jpg)

Translation:
https://github.com/MohGovIL/hamagen-react-native/blob/e5606f3040c47b5c2713d432280273a99bcb2285/src/locale/texts.json#L1310-L1314

Context:
![3](https://user-images.githubusercontent.com/2017058/87294214-0efd9280-c50c-11ea-8b93-131ac1f3b4e0.jpg)

Translation:
https://github.com/MohGovIL/hamagen-react-native/blob/e5606f3040c47b5c2713d432280273a99bcb2285/src/locale/texts.json#L1305-L1308

Context:
![4](https://user-images.githubusercontent.com/2017058/87294221-115fec80-c50c-11ea-9bc6-65608c7684c7.jpg)

**Comment by getalew90** [comment]
אני כאן כדי לעזור , ניתן ליצור איתי קשר

**Comment by kaplanlior** [comment]
> אני כאן כדי לעזור , ניתן ליצור איתי קשר

בשמחה, רק צריך פרטי קשר (טלפון/מייל וכו') כי אין אפשרות לשלוח הודעה דרך github אליך . אפשר גם לשלוח לי הודעה פרטית.
