### ISSUE TITLE
Mention shallow clone

### ISSUE THREAD

**Issue by emanuelb** [MohGovIL/hamagen-react-native#279]
From CONTRIBUTING.md:

```
1. [Fork this repository](https://github.com/MohGovIL/hamagen-react-native/) and then clone it locally:

  `git clone https://github.com/<yourUserName>/hamagen-react-native/`
 ```

There no mention of shallow clone (adding parameter `--depth 1 --no-tags`) to reduce bandwidth by avoiding downloading history if not needed, something like:

```

for building master (no history needed) use:
`git clone --depth 1 --no-tags https://github.com/MohGovIL/hamagen-react-native`

only if full history is needed use:

`git clone https://github.com/MohGovIL/hamagen-react-native`

```

**Comment by kaplanlior** [comment]
The user is free to choose the way he wants and to optimize it. From our side, as long as he has a clone, we're fine. No need to try and cover all possible use cases (e.g. lower bandwidth).
