### ISSUE TITLE
Access the raw data the app compares to

### ISSUE THREAD

**Issue by tsvikas** [MohGovIL/hamagen-react-native#28]
How can one download the data of previous cases, to compare with it? I can export my location history to JSON, and I plan to write a program to locally compare it to your database. Is it possible to get the sick cases locations raw data?

**Comment by MiriShalev** [comment]
Hey @tsvikas . Exporting the last 14 days from Google's Timelint (Location History) is a feature we're working on. 
Nevertheless, here's how to get the sick cases locations raw data:

~~~bash
$ curl https://gisweb.azureedge.net/Points.json
~~~

**Comment by aelburg** [comment]
Hi @MiriShalev , Please enable longer periods from Google's timeline. 14 days is enough for compulsory isolation, but users may want to check a bit older history. just to be on the safe side. or for any other reason.
Also, what about correlating user's path against known sick paths abroad? (Example, person arrived in Israel 1 week ago. - so you correlate hos last week against known paths in Israel, but what about his time abroad? Maybe he came from a place where they also investigate and publish epidemiological paths, So you or the user can import specifically that country's info and check his path abroad as well.
