### ISSUE TITLE
Use a .env (or any other non tracked store) for firebase credentials

### ISSUE THREAD

**Issue by bajayo** [MohGovIL/hamagen-react-native#3]
Storing all firebase, and other credentials in the code is a possible hazard. Please create new Auth clients, move their credentials to a .env, git ignore it first of course, and use Process.ENV to fill credentials on build.

Example file:
https://github.com/MohGovIL/hamagen-react-native/blob/master/android/app/src/release/google-services.json

**Comment by omerxx** [comment]
I believe it should also be deleted from the tree's history and of course, rotated too

**Comment by MiriShalev** [comment]
@bajayo  and @omerxx  thanks for pointing that out. We've researched the subject and found multiple sources that state that it is **safe** to check `google-services.json` in your source control:

For instance, by a Firebsae engineer:  https://groups.google.com/forum/#!msg/firebase-talk/bamCgTDajkw/uVEJXjtiBwAJ
