### ISSUE TITLE
iPhone SE - Unable to complete onboarding and unsupported screen size

### ISSUE THREAD

**Issue by Norod** [MohGovIL/hamagen-react-native#31]
Launch screen gets over scaled:

![image](https://user-images.githubusercontent.com/3617152/77286822-c3b14100-6cdc-11ea-9e04-253621a259b1.png)

`The iPhone SE is equipped with a 4‑inch (diagonal) LED‑backlit widescreen Multi‑Touch Retina display with 1136‑by‑640‑pixel resolution at 326 ppi.`

After which user is stuck in the following screen, where the checkbox can be marked but no location privacy prompt is popping. Off screen button which needs to be tapped?

**Comment by Norod** [comment]
Unable to proceed, no privacy prompt
Hebrew:
![image](https://user-images.githubusercontent.com/3617152/77287513-6f0ec580-6cde-11ea-8d5c-10b3dacf9a5e.png)
English:
![image](https://user-images.githubusercontent.com/3617152/77287537-7afa8780-6cde-11ea-8d2d-a523f88efe54.png)

**Comment by galaktipus** [comment]
This also happens with any iOS device with a screen less than 4.7inch. (ie: iPhone 5, 5s, SE)

**Comment by greenyossi** [comment]
Fixed in 1.0.22
