### ISSUE TITLE
App doesn't support french

### ISSUE THREAD

**Issue by LioraLevy** [MohGovIL/hamagen-react-native#4]
I'll be happy to fix it and contribute

**Comment by YOEL311** [comment]
lets start
I don't know French
But I will help you in implementing it

https://github.com/MohGovIL/hamagen-react-native/blob/9468888ba617b015b8fa4c938e784c9be48dbfd8/src/locale/texts.json#L3

**Comment by YOEL311** [comment]
and here

https://github.com/MohGovIL/hamagen-react-native/blob/9468888ba617b015b8fa4c938e784c9be48dbfd8/src/config/config.ts#L20

**Comment by LioraLevy** [comment]
I know french and I am a fullstack engineer

I have all the code done
is texts.json
+
in ChangeLanguage.tsx

But when trying to push to my branch I get a permission denied error

**Comment by Plutoberth** [comment]
> I know french and I am a fullstack engineer
> 
> I have all the code done
> is texts.json
> +
> in ChangeLanguage.tsx
> 
> But when trying to push to my branch I get a permission denied error

I think that you're probably pushing to a branch in this repository, which you don't have access to. You need to fork and make a pull request.

**Comment by YOEL311** [comment]
git checkout -b fix-for-add-franch

https://gitlab.com/CodeAgainstCorona/hamagen/-/blob/master/CONTRIBUTING.md

**Comment by LioraLevy** [comment]
its ok I forgot to fork the branch
There a Pull request ready : https://github.com/MohGovIL/hamagen-react-native/pull/11

**Comment by greenyossi** [comment]
We've added French to the next release, Thanks!

**Comment by LioraLevy** [comment]
Thanks
I've seen this on thursday on my PR 
Do you know when the next release will be available? 
Thanks?
