### ISSUE TITLE
Getting and SSL error when opening privacy policy

### ISSUE THREAD

**Issue by amanusk** [MohGovIL/hamagen-react-native#42]
OS: iOS
Device: iPhone X
Upon clicking on privacy policy (both on initial setup and in the app). I am getting the following screen:
![IMG_DD87CFD4B5F1-1](https://user-images.githubusercontent.com/7280933/77294951-c700f880-6ced-11ea-8c10-2605dba404f1.jpeg)

**Comment by dotansimha** [comment]
@amanusk @MiriShalev I tried to fix this issue in this PR: https://github.com/MohGovIL/hamagen-react-native/pull/49

**Comment by greenyossi** [comment]
Fixed in 1.0.20.
