### ISSUE TITLE
Can't download android app in google play (non-Israeli google play account)

### ISSUE THREAD

**Issue by ey51** [MohGovIL/hamagen-react-native#47]
- People with a non-Israeli google play store account can't get the app.
- [ ] Can you guys make a compiled apk available on your github releases, for people unable to get it from the google play store?
thanks!

![image](https://user-images.githubusercontent.com/39327343/77296838-0c72f500-6cf1-11ea-8b77-f3d7872d8c1e.png)

**Comment by elichai** [comment]
Already fixed. google play just takes some time
https://github.com/MohGovIL/hamagen-react-native/issues/10

**Comment by ey51** [comment]
thanks. QUICK GOOGLE PLAY, while we wait patiently, the corona washes us like a storm!. =)
