### ISSUE TITLE
iPhone 6, iOS 10.3.3 - Text issues

### ISSUE THREAD

**Issue by vikidish** [MohGovIL/hamagen-react-native#50]
The info text about being exposed is overlapping and is hard to read. This problem is present only in Hebrew and English, Russian and Arabic seems to be fine. 
(Also, the fifth language seems to be missing encoding and therefore shows question marks)

iPhone 6, iOS 10.3.3, app ver. 1.0.20 (updated on 23/3/2020)

![magen_textover_bug_1 0 20](https://user-images.githubusercontent.com/30635610/77296695-ce75d100-6cf0-11ea-84e2-4c503a8caadb.jpg)

![magen_encoding_bug_1 0 20](https://user-images.githubusercontent.com/30635610/77297800-7e980980-6cf2-11ea-8c5b-f1f1efd16a57.jpg)

**Comment by MiriShalev** [comment]
Closed by #93 . @vikidish can you please verify it works for you?
