### ISSUE TITLE
Enable access for non-Israel app stores

### ISSUE THREAD

**Issue by niryariv** [MohGovIL/hamagen-react-native#56]
At least on the Play store, I'm not able to install the app because my account is linked to the US store.

I suspect this is the cause of most problems at #26 - the store message make it seem like a device issue, but I'm on a clean Android on Pixel 3a so I doubt that's the cause.

**Comment by 5ay3h** [comment]
Same issue. Screenshot: 
![image](https://user-images.githubusercontent.com/9954472/77303729-18b07f80-6cfc-11ea-9271-2edac7aad06e.png)

**Comment by dotansimha** [comment]
For now, you can bypass it by downloading it from a third-party that mirrors the app store, something like: https://apk.support/app/com.hamagen 

On a general note, I understand the curiosity, but it might not help you if you are not located in Israel...

**Comment by BrzezinaTzanani** [comment]
I'm in Israel right now, and my account is linked to Israel.
Can't download, though.

https://support.google.com/googleplay/answer/7431675?hl=iw

**Comment by shaked113021** [comment]
> I'm in Israel right now, and my account is linked to Israel.
> Can't download, though.
> 
> https://support.google.com/googleplay/answer/7431675?hl=iw

Can you send a screenshot of the problem?

**Comment by 5ay3h** [comment]
> Edit: if you are on Android please try creating a new Google account or switching to another, it happend to me before with other apps and that seems to always solve the problem for me.

This is not possible for some of us

**Comment by niryariv** [comment]
Issue fixed AFAI can tell. (ie, installing on my device without problem from the US Play store)
