### ISSUE TITLE
Points.json only has one point on bus/train rides - false negatives

### ISSUE THREAD

**Issue by yoavw** [MohGovIL/hamagen-react-native#6]
On bus rides with multiple stops, having only one point causes partial route overlaps to be missed.

Suggested fix: include an additional point, 20 meters before and after each bus stop along the route, to detect partial overlaps.  20 meters away from the stop, not at the stop itself, to avoid false positives when a sick person is on a bus, and the user is standing in the bus stop waiting for another bus.  Alert only if both points between two stops are positive, which indicates that both passengers were indeed on the same bus.

**Comment by MiriShalev** [comment]
Thanks for pointing that out. We're aware of this. In the following days we expect to retrieve validated COVID-19 patients location data in a richer format (but still preserve their privacy), one which supports efficient geoqueries. We'll update more on this when we know more.
