### ISSUE TITLE
Collecting WiFi information without using it

### ISSUE THREAD

**Issue by yannayl** [MohGovIL/hamagen-react-native#64]
The application collects the user WiFi information to the database but doesn't make any use of it.

**Comment by MiriShalev** [comment]
Hey, yes! We  **locally** collect the WIFI BSSIDs  around. The main idea is that GPS is great for **outdoor** intersection detection, but terrible for **indoor**. COVID-19 usually passes by people in confined spaces (indoor). Collecting BSSIDs would allow us, to some extent, an **indoor** intersection detection.

There're more ideas we're considering for **indoor** detection - bluetooth, data over sound, etc.

We don't have an ETA for this feature yet.

**Comment by yannayl** [comment]
`react-native-background-geolocation` already uses the WiFi information when [configured to DESIRED_ACCURACY_HIGH](https://github.com/MohGovIL/hamagen-react-native/blob/c59aa1669deb2c20fbe229f65f6d812aa096df43/src/services/LocationService.ts#L59), see the [documentation](https://github.com/transistorsoft/react-native-background-geolocation/blob/8f6bf01f17e3532b5b2665dcedba75ecefadff42/help/README.md#wrench-geolocation-common-options).
You are not using the GPS directly, you are using the OS location API which already takes the WiFi information into account.

**Comment by MiriShalev** [comment]
I don't understand your point. The output of `react-native-background-geolocation` is GPS coordinates - regardless of the accuracy we set. Also, we are agnostic to the WIFI info that the underlying OS location api (e.g. FusedLocation) uses.  

This is a simple feature that was meant to assess distance between people. We'll probably use BLE and retire it anyway.

**Comment by deantheiceman** [comment]
Hi @MiriShalev what was the reason for retiring this feature? Was the wifi feature unreliable?
