### ISSUE TITLE
is the Points.json file up-to-date?

### ISSUE THREAD

**Issue by boynet** [MohGovIL/hamagen-react-native#69]
for example in [this message](https://www.gov.il/he/departments/news/23032020_04) about corona in rishon lezion you can see 

> "14.3: בשעות 19:30-19:45 חנות דקתלון רחוב הלחי 4, בראשון לציון" 

which is no where to be found in the [points.json](https://matrixdemos.blob.core.windows.net/mabar/Points.json) file

**Comment by MiriShalev** [comment]
There's a team of people that works to "geocode" validated COVID-19 patients location data. When they update their GIS system the JSON should be updated (there should be a 300 seconds max-age on the file).

By the way, this is the correct url:

~~~
$ curl https://gisweb.azureedge.net/Points.json
~~~

**Comment by boynet** [comment]
> https://gisweb.azureedge.net/Points.json

this file also doesn't have the "חנות דקתלון" place(it was published few hours ago)

**Comment by MiriShalev** [comment]
You're absolutely right. There seem to be a bottleneck with the team that updates the GIS system. We're talking to them.

**Comment by kaplanlior** [comment]
Much of the GIS information is done by volunteer's work. Many thanks to them.
