### ISSUE TITLE
APK availability

### ISSUE THREAD

**Issue by vcorem** [MohGovIL/hamagen-react-native#72]
Will you publish compiled APK for non-Google Play phones?
(e.g https://grapheneos.org/)

**Comment by budowski** [comment]
The best thing would also to provide this as part of each release page (as an artifacts):
https://github.com/MohGovIL/hamagen-react-native/releases/

**Comment by AlmaMOH** [comment]
Hey @vcorem  and @budowski ,

We'd like that very much! Closing this issue, we'll consolidate on #96 and #97 .
