### ISSUE TITLE
The sick case number is missing from Points.json

### ISSUE THREAD

**Issue by ofekashery** [MohGovIL/hamagen-react-native#73]
In the [``Points.json``](https://gisweb.azureedge.net/Points.json) file, each exposure object should contain the _sick case number_ in the ``Name`` property,  under the ``properties``, as you use it [here](https://github.com/MohGovIL/hamagen-react-native/blob/584918cffc61836d6543bba85083f2eac6e41e15/src/components/Main/ExposuresDetected.tsx#L49).

<hr/>

```json
{
  "type": "Feature",
  "id": 7031,
  "geometry": {
    "type": "Point",
    "coordinates": [
      34.9617953000001,
      32.3125987
    ]
  },
  "properties": {
    "OBJECTID": 7031,
    "Name": MISSING,
    "Place": "סופרמרקט חינם פלוס צומת תנובות ",
    "Comments": "",
    "POINT_X": 34.9617953,
    "POINT_Y": 32.3125987,
    "fromTime": 1583677800000,
    "toTime": 1583681400000,
    "sourceOID": 1,
    "stayTimes": "14:30-15:30"
  }
}
```

**Comment by kaplanlior** [comment]
You're right. But that's for past data. Current data published at https://govextra.gov.il/ministry-of-health/corona/corona-virus/spokesman-messages-corona/ doesn't have patient ID / case number any more.
