### ISSUE TITLE
feature request: import google location history

### ISSUE THREAD

**Issue by mottibec** [MohGovIL/hamagen-react-native#76]
Personal location history can be downloaded from [here](https://takeout.google.com)

**Comment by MiriShalev** [comment]
Hey, we're working on extracting the last 14 days.

Google doesn't provide an API for this, but we found a trick to extract those locations using a WebView. Stay tuned!

**Comment by Yshayy** [comment]
Hi @MiriShalev,
I've also investigated extracting this data using webview with script injection, feel free to look here:
https://github.com/Yshayy/hamagen-react-native/blob/master/src/components/Main/ImportData.tsx

The webview extraction worked and all the data is passed to react-native, I'm in the middle of integrating it to other parts of the app (a bit wrapped in the details of adding historic data).
