### ISSUE TITLE
"No data detected" on first try right after  start.

### ISSUE THREAD

**Issue by arielgee** [MohGovIL/hamagen-react-native#78]
This is strange.

When I start the app I get "No data detected". To fix that all I need to do is turn off the Wi-Fi and switch to mobile data and I get results.

It's the same the other way around. If I start with mobile data I get results only when I turn on Wi-Fi.

I use Pixel 2 XL. fully updated.

**Comment by ReuvenMash** [comment]
same on Xiaomi 9t

**Comment by arielgee** [comment]
The problem was resolved after I cleared the app's storage & cache.

See here: https://github.com/MohGovIL/hamagen-react-native/issues/120

**Comment by AlmaMOH** [comment]
Closing this. See #120. If anything is still wrong, please let us know!
