### ISSUE TITLE
I don't see any service running while the app is in background

### ISSUE THREAD

**Issue by tRamboli** [MohGovIL/hamagen-react-native#81]
I just downloaded the app from the Google Play, set it all as needed with the permissions. When I exit the app, it doesn't show in the current active services in the Android settings menu. I'm afraid that the app can't collect GPS data while it's on the background.

As much as I know, Android nowadays permit running on background only apps that shows notification icon constantly, with always shown notification, and I don't see it.

Thanks

**Comment by YOEL311** [comment]
I think this happens 
because the service runs evry few minutes

https://github.com/MohGovIL/hamagen-react-native/blob/3c6695c2b2cab3bb00a1e1b2b39a5fab18fb2f93/src/services/BackgroundService.ts#L10

**Comment by MiriShalev** [comment]
@tRamboli The app is running all the time while your GPS is on. We are constantly improving the user experience on this issue.
