### ISSUE TITLE
[ENHANCEMENT] Use Squash & Merge for better commit history 

### ISSUE THREAD

**Issue by Attrash-Islam** [MohGovIL/hamagen-react-native#82]
Hi,

If we're looking to the commits log in the master we can see that all commits are being recorded even if they come from the same PR (If I done 10 commits in one PR then I'll see them all in the commit log).

![image](https://user-images.githubusercontent.com/7091543/77366432-aaea6f00-6d60-11ea-8b22-1d918deb6c99.png)

It's more better to adapt the strategy "Squash & Merge" in order to keep the master commit log more cleaner (You're already using PRs which will contain the commits grouped for that specific feature/bugfix).

That can be configured through the settings of the repository.

**Comment by MiriShalev** [comment]
Thanks @Attrash-Islam ! We'll try to "Squash & Merge" from now on.

**Comment by Attrash-Islam** [comment]
Perfect! Thanks 👍
