### ISSUE TITLE
How is this related to Private Kit?

### ISSUE THREAD

**Issue by oren** [MohGovIL/hamagen-react-native#87]
Is Hamagen meant to be used in Israel and outside it's better to use Private Kit?
https://github.com/tripleblindmarket/private-kit

**Comment by MiriShalev** [comment]
Hey @oren , Hamagen isn't related to Private Key - though they do share similar privacy properties. 

Hamagen by Israel's Ministry of Health and therefore is primarly aimed for Israelis. That being said, Hamagen can be easily adapted to serve other countries (hence the MIT license).
