### ISSUE TITLE
Why is the app saving Wifi MAC addresses and SSID hash in the DB?

### ISSUE THREAD

**Issue by ta1m** [MohGovIL/hamagen-react-native#89]
I noticed it is saving WIFI access point info in the local DB, but not using it to compare with points data. Can you explain?

**Comment by MiriShalev** [comment]
Please see https://github.com/MohGovIL/hamagen-react-native/issues/64#issuecomment-602529668

**Comment by ta1m** [comment]
Maybe you should let users know that they are being tracked even if they turn location off, or they go into a closed place on purpose to avoid tracking. It's a privacy issue.

**Comment by MiriShalev** [comment]
I think you're right. I'll pass it along. Thanks!

**Comment by ta1m** [comment]
Cool, thanks :)
