### ISSUE TITLE
Requirement within function Causes lazy loading

### ISSUE THREAD

**Issue by YOEL311** [MohGovIL/hamagen-react-native#9]
https://github.com/MohGovIL/hamagen-react-native/blob/9468888ba617b015b8fa4c938e784c9be48dbfd8/src/services/Tracker.ts#L42

**Comment by MiriShalev** [comment]
Thanks for spotting this @YOEL311 . Can you please submit a PR?

**Comment by YOEL311** [comment]
I did PR

https://github.com/MohGovIL/hamagen-react-native/pull/14

**Comment by YOEL311** [comment]
fixed
