### ISSUE TITLE
F-Droid app?

### ISSUE THREAD

**Issue by 456ygr67ugrty** [MohGovIL/hamagen-react-native#91]
Hi, can you please upload the app to f-droid? Or make the .apk available. Or instructions to build it. Thanks.

**Comment by AlmaMOH** [comment]
Hey @456ygr67ugrty , 

We'll probably have the APK when we finish the deploying a working CI CD system.

Regarding building the APK yourself, please [use the following instructions](https://dev.to/zilurrane/generate-release-mode-apk-for-react-native-project-to-publish-on-playstore-5f78)
